[package]
name = "iota-streams-core"
version = "0.2.0"
authors = ["Vlad Semenov <vlad.semenov@iota.org>"]
edition = "2018"
license = "Apache-2.0/MIT"
readme = "README.md"
keywords = ["iota", "streams", "core"]
description = "A rust implementation of the IOTA Streams core utils"

[lib]
name = "iota_streams_core"
path = "src/lib.rs"

[dependencies]
# digest version should correspond to curve25519-dalek's version
digest = { version = "0.8", default-features = false }
rand = "0.7"

[dev-dependencies]
criterion = "0.3"
