#cargo-features = ["named-profiles"]

[package]
name = "iota-streams"
version = "0.2.0"
authors = ["Vlad Semenov <vlad.semenov@iota.org>"]
edition = "2018"
license = "Apache-2.0/MIT"
readme = "README.md"
keywords = ["iota", "streams"]
description = "A rust implementation of the IOTA Streams"

[lib]
name = "iota_streams"

[workspace]
members = [
    "iota-streams-core",
    "iota-streams-core-edsig",
    "iota-streams-core-keccak",
    "iota-streams-ddml",
    "iota-streams-app",
    "iota-streams-app-channels",
    "iota-streams-app-channels-example",
    #"iota-streams-app-channels-js",
]

[dependencies]
iota-streams-core = { version = "0.2.0", path = "iota-streams-core" }
iota-streams-core-keccak = { version = "0.2.0", path = "iota-streams-core-keccak" }
iota-streams-core-edsig = { version = "0.2.0", path = "iota-streams-core-edsig" }
iota-streams-ddml = { version = "0.2.0", path = "iota-streams-ddml" }
iota-streams-app = { version = "0.2.0", path = "iota-streams-app" }
iota-streams-app-channels = { version = "0.2.0", path = "iota-streams-app-channels" }

#[profile.release-nostd]
#inherits = "release"
#opt-level = 's'
#debug = false
#rpath = false
#lto = true
#debug-assertions = false
#codegen-units = 1
#panic = "abort"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
