[package]
name = "iota-streams-protobuf3"
version = "0.2.0"
authors = ["Vlad Semenov <vlad.semenov@iota.org>"]
edition = "2018"
license = "Apache-2.0/MIT"
readme = "README.md"
keywords = ["iota", "streams", "protobuf3"]
description = "A rust implementation of the IOTA Streams Protobuf3"

[features]
default = ["std"]
# enable std
std = ["rand/std", "iota-streams-core/std", "iota-streams-core-edsig/std", "digest/std", "anyhow/std"]

[lib]
name = "iota_streams_protobuf3"
path = "src/lib.rs"

[dependencies]
iota-streams-core = { version = "0.2.0", path = "../iota-streams-core", default-features = false }
iota-streams-core-edsig = { version = "0.2.0", path = "../iota-streams-core-edsig", default-features = false }
# anyhow version is kept in sync with iota-core
anyhow = { version = "1.0.26", default-features = false }
# digest version should correspond to curve25519-dalek's version
digest = { version = "0.8", default-features = false }
rand = { version = "0.7", default-features = false }
hashbrown = { version = "0.8.2", default-features = false, optional = false, features = ["ahash"] }

[dev-dependencies]
iota-streams-core-keccak = { version = "0.2.0", path = "../iota-streams-core-keccak" }
