[package]
name = "iota-streams-app-channels-example"
version = "0.1.0"
authors = ["Vlad Semenov <semenov.vlad.by@gmail.com>"]
edition = "2018"

[features]
default = ["std"]
# enable std
std = ["iota-streams/std"]
async = ["iota-streams/async"]
tangle = ["iota-streams/tangle"]

[dependencies]
wee_alloc = "0.4.5"
iota-streams = { version = "0.3.0", path = "..", default-features = false }
