[package]
name = "iota-streams-app-channels"
version = "0.2.0"
authors = ["Vlad Semenov <vlad.semenov@iota.org>"]
edition = "2018"
license = "Apache-2.0/MIT"
readme = "README.md"
keywords = ["iota", "streams", "app", "channels"]
description = "A rust implementation of the IOTA Streams Channels Application"

[features]
default = ["std", "async", "tangle"]
# enable std
std = ["iota-streams-core/std", "iota-streams-core-edsig/std", "iota-streams-protobuf3/std", "iota-streams-app/std", "anyhow/std"]
async = ["iota-streams-app/async"]
tangle = ["iota-streams-app/tangle"]

[lib]
name = "iota_streams_app_channels"
path = "src/lib.rs"

[dependencies]
iota-streams-core = { version = "0.2.0", path = "../iota-streams-core", default-features = false }
iota-streams-core-edsig = { version = "0.2.0", path = "../iota-streams-core-edsig", default-features = false }
iota-streams-core-keccak = { version = "0.2.0", path = "../iota-streams-core-keccak", default-features = false }
iota-streams-protobuf3 = { version = "0.2.0", path = "../iota-streams-protobuf3", default-features = false }
iota-streams-app = { version = "0.2.0", path = "../iota-streams-app", default-features = false }
anyhow = { version = "1.0.26", default-features = false }
