[package]
name = "iota-streams-app"
version = "1.0.1"
authors = ["Vlad Semenov <vlad.semenov@iota.org>", "Dyrell Chapman <dyrell.chapman@iota.org>", "Brord van Wierst <brord@iota.org>"]
edition = "2018"
license = "Apache-2.0/MIT"
readme = "README.md"
keywords = ["iota", "streams", "app"]
description = "A rust implementation of the IOTA Streams applications"

[features]
default = ["std", "client"]
# Enable `std` feature in dependencies
std = ["iota-streams-core/std", "iota-streams-core-edsig/std", "iota-streams-ddml/std", "chrono/std", "chrono/clock", "hex/std"]
# Enable Tangle-specific transport abstractions
tangle = ["chrono", "num_cpus"]
# Enable Tangle transport client implementation (implies `tangle` and `std` features)
client = ["iota-client/async", "futures", "tangle", "std"]
# Enable Tangle wasm-compatible client implementation (incompatile with `client` feature due to `iota-client/async` using `tokio`)
wasm-client = ["iota-client/wasm", "chrono/wasmbind", "futures", "tangle", "std"]
# Enable synchronized transports using parking-lot
sync-parking-lot = ["iota-streams-core/sync-parking-lot"]
# Enable synchronized transports using spin 
sync-spin = ["iota-streams-core/sync-spin"]

[lib]
name = "iota_streams_app"
path = "src/lib.rs"

[dependencies]
iota-streams-core = { version = "0.3.1", path = "../iota-streams-core", default-features = false }
iota-streams-core-edsig = { version = "0.2.1", path = "../iota-streams-core-edsig", default-features = false }
iota-streams-ddml = { version = "0.2.1", path = "../iota-streams-ddml", default-features = false }

# anyhow and chrono are kept in sync with versions used in iota-client
anyhow = { version = "1.0.26", default-features = false }
chrono = { version = "0.4.11", default-features = false, optional = true }
hex = { version = "0.4", default-features = false, optional = false }
futures = { version = "0.3.8", default-features = false, features = ["executor"], optional = true }

# Dependencies for "client" feature
iota-client = { git = "https://github.com/iotaledger/iota.rs", rev  = "c9fdc7e7d5bccd32a1f4958a1563653d9eb6ea74", default-features = false, optional = true }

num_cpus = { version = "1.10", optional = true }

cstr_core = { version = "0.2.2", default-features = false, features = ["alloc"] }
cty = { version = "0.2.1" }
