[package]
name = "iota-streams-app"
version = "0.2.0"
authors = ["Vlad Semenov <vlad.semenov@iota.org>"]
edition = "2018"
license = "Apache-2.0/MIT"
readme = "README.md"
keywords = ["iota", "streams", "app"]
description = "A rust implementation of the IOTA Streams applications"

[lib]
name = "iota_streams_app"
path = "src/lib.rs"

[dependencies]
iota-streams-core = { version = "0.2.0", path = "../iota-streams-core" }
iota-streams-core-edsig = { version = "0.1.0", path = "../iota-streams-core-edsig" }
iota-streams-protobuf3 = { version = "0.2.0", path = "../iota-streams-protobuf3" }
# `iota-core` crate is WIP with unstable API atm of writing.
iota-core = { git = "https://github.com/iotaledger/iota.rs", rev = "d5592273" }
iota-constants = { version = "0.2.1" }
iota-conversion = { version = "0.5.0" }
# anyhow and chrono are kept in sync with versions used in iota-core
anyhow = "1.0.26"
chrono = "0.4.11"
smol = "0.1.7"
hex = "0.4.2"
