[package]
name = "iota-streams-app"
version = "0.2.0"
authors = ["Vlad Semenov <vlad.semenov@iota.org>"]
edition = "2018"
license = "Apache-2.0/MIT"
readme = "README.md"
keywords = ["iota", "streams", "app"]
description = "A rust implementation of the IOTA Streams applications"

[features]
default = ["std", "async"]
# enable std
std = ["iota-streams-core/std", "iota-streams-core-edsig/std", "iota-streams-protobuf3/std", "anyhow/std"]
async = ["core"]

[lib]
name = "iota_streams_app"
path = "src/lib.rs"

[dependencies]
iota-streams-core = { version = "0.2.0", path = "../iota-streams-core", default-features = false }
iota-streams-core-edsig = { version = "0.2.0", path = "../iota-streams-core-edsig", default-features = false }
iota-streams-protobuf3 = { version = "0.2.0", path = "../iota-streams-protobuf3", default-features = false }
# `iota-core` crate is WIP with unstable API atm of writing.
iota-core = { git = "https://github.com/iotaledger/iota.rs", rev = "03cf531" }

iota-constants = { version = "0.2.1" }
#iota-conversion = { version = "0.5.0" }

# anyhow and chrono are kept in sync with versions used in iota-core
anyhow = { version = "1.0.26", default-features = false }
chrono = "0.4.11"

# feature tokio02 explicitly required for block_on calls
smol = {version = "0.1.18", features = ["tokio02"]}
core = { package = "core-futures-tls", version = "0.1.1", path = "../../core-futures-tls", optional = true }
num_cpus = "1.10"
hex = "0.4.2"
